apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxds
  namespace: test 
spec:
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      name: nginxpod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key:  node-role.kubernetes.io/control-plane
        operator: "Exists"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  namespace: test 
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
