apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot 
  template:
    metadata:
      labels:
        app: springboot
    spec: 
      containers:
      - name: springboot-container
        image: dockerhandson/spring-boot-mongo:1 
        resources:
          requests:
            memory: "350Mi"
            cpu: "300m"
          limits:
            memory: "428Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_PASSWORD
          value: root
        - name: MONGO_DB_USERNAME
          value: admin
        - name: MONGO_DB_HOSTNAME
          value: mongodbsvc
---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30006
    name: springboot
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongors 
  namespace: test
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
      - name: mongodbdatavol
        hostPath:
         path: "/C/Users/Vikas/Documents/k8s/mongodbvolume"
         type: Directory
      containers:
        - name: mongodb-container
          image: mongo
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
          - containerPort: 27017
          volumeMounts:
          - name: mongodbdatavol
            mountPath: "/data/db"
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin
            - name: MONGO_DB_HOSTNAME
              value: mongodbsvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
  namespace: test
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017