apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  namespace: assignment-namespace
  labels:
    name: myapp
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
          requests:
            cpu: "300m"
            memory: "450Mi"
          limits:
            memory: "550Mi"
            cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: log-volume
        mountPath: /var/log/nginx
  - name: log-sidecar
    image: busybox
    resources:
          requests:
            cpu: "300m"
            memory: "450Mi"
          limits:
            memory: "550Mi"
            cpu: "500m"
    command: ["sh", "-c", "tail -f /var/log/nginx/access.log"]
    volumeMounts:
      - name: log-volume
        mountPath: /var/log/nginx
  volumes:
  - name: log-volume
    emptyDir: {}
