apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - javawebapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: storages
                operator: In
                values:
                - SSDs
      containers:
      - name: javawebapp-container
        image: dockerhandson/java-web-app:2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: javawebapp
    nodePort: 30004