---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - javawebapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      imagePullSecrets:
      - name: dockerhubsecret
      containers:
      - name: javawebapp-container
        image: prcdocker/privaterepo:1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tomcatconfig
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"      
      volumes:
      - name: tomcatconfig
        configMap:
          name: javaconfig
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: javawebapp
    nodePort: 30004