apiVersion: v1 
kind: ReplicationController
metadata:
 name: mavenapplication
 namespace: test 
spec:
  replicas: 3
  selector:
   app: mavenweapp
  template:
   metadata:
     name: mavenwebapppod
     labels:
      app: mavenweapp
   spec:
    containers:
      - name: mavenweappcontainer
        image: prcdocker/java-web-docker:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: test
spec:
  type: NodePort
  selector:
    app: mavenweapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001