apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
  namespace: test 
spec:
  selector:
    matchLabels:
      app: maven   
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: mavencontainer
        image: prcdocker/maven-web-application:multistagedockerfile
        resources:
          requests:
            cpu: "200m"
            memory: "250Mi"
          limits:
            memory: "550Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
  namespace: test 
spec:
  type: NodePort
  selector:
    app: maven
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002