apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
spec:
  replicas: 1
  selector:
    app: nodejs
  template:
    metadata:
      name:  nodejsapplication
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejsapplication
          image: dockerhandson/node-app-mss:6
          ports:
            - containerPort: 9981
---
apiVersion: v1
kind: Service
metadata:
  name: nodejswebappsvc
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
  - port: 80
    targetPort: 9981
    nodePort: 30005
