apiVersion: apps/v1
kind: Deployment
metadata:
  name: javdeployment
  namespace: test 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java   
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: mavencontainer
        image: prcdocker/java-web-docker:1
        resources:
          requests:
            cpu: "200m"
            memory: "200Mi"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapp
  namespace: test 
spec:
  type: NodePort
  selector:
    app: java
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003

