apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: dockerhandson/spring-boot-mongo:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_PASSWORD
          value: devdb123
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_HOSTNAME
          value: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: test
spec:
  type: NodePort
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
    name: springboot